package com.phptravels.pages;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class GeneratePasswordModal {
    private final WebDriver driver;
    private final WebDriverWait wait;

    @FindBy(xpath = "//button[normalize-space()='Generate new password']")
    private WebElement generateNewPasswordButton;

    @FindBy(id = "btnGeneratePasswordInsert")
    private WebElement copyToClipboardAndInsertButton;

    @FindBy(xpath = "//button[normalize-space()='Copy']")
    private WebElement copyButton;

    @FindBy(id = "inputGeneratePasswordOutput")
    private WebElement generatedPasswordField;

    public GeneratePasswordModal(WebDriver driver, WebDriverWait wait) {
        this.driver = driver;
        this.wait = wait;
    }

    public String autoGeneratePassword() {
        //TODO insert password size
        wait.until(ExpectedConditions.elementToBeClickable(generateNewPasswordButton)).click();
        wait.until(ExpectedConditions.elementToBeClickable(copyButton)).click();
        String textOfAutogeneratedPassword = getTextOfAutogeneratedPassword();
        wait.until(ExpectedConditions.elementToBeClickable(copyToClipboardAndInsertButton)).click();
        return textOfAutogeneratedPassword;
    }

    public String getTextOfAutogeneratedPassword() {
        String textOfAutogeneratedPassword = generatedPasswordField.getAttribute("value");
        return textOfAutogeneratedPassword;
    }

}
