package com.phptravels;

import com.phptravels.pages.ChangePasswordPage;
import com.phptravels.pages.LoginPage;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import static org.testng.Assert.assertTrue;

public class ChangePasswordTest extends TestSetup {
    private String autogeneratedPassword;

    @BeforeTest
    public void loginBeforeTest() throws InterruptedException {
        LoginPage loginPage = new LoginPage(driver).get();
        loginPage.loginAs(email, password);
    }

    @Test
    public void logged_user_can_change_its_password_with_autogenerated_one() {
        //ARRANGE
        ChangePasswordPage changePasswordPage = new ChangePasswordPage(driver, wait).get();

        //ACT
        autogeneratedPassword = changePasswordPage.changePassword(password);
        System.out.println(autogeneratedPassword);

        //ASSERT
        assertTrue(changePasswordPage.isDisplayedCorrectly());
    }

    @AfterTest
    public void revert_password_to_original_one() {
        ChangePasswordPage changePasswordPage = new ChangePasswordPage(driver, wait).get();
        changePasswordPage.manualPasswordChange(autogeneratedPassword, password);
    }
}
