package com.phptravels;

import com.phptravels.pages.ChangePasswordPage;
import org.testng.annotations.AfterTest;
import org.testng.annotations.Test;

import static org.testng.Assert.assertTrue;

public class ChangePasswordTest extends TestSetup {
    private String autogeneratedPassword;

    @Test
    public void logged_user_can_change_its_password_with_autogenerated_one() throws InterruptedException {
        //ARRANGE
        loginBeforeTest();
        ChangePasswordPage changePasswordPage = new ChangePasswordPage(driver, wait).get();

        //ACT
        autogeneratedPassword = changePasswordPage.changePassword(password);

        //ASSERT
        assertTrue(changePasswordPage.isDisplayedCorrectly());
        assertTrue(changePasswordPage.isSuccessMessageDisplayed());
    }

    @AfterTest
    public void revert_password_to_original_one() {
        ChangePasswordPage changePasswordPage = new ChangePasswordPage(driver, wait).get();
        changePasswordPage.manualPasswordChange(autogeneratedPassword, password);
    }
}
